service: serverless-ts-apollo-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  auth:
    handler: src/handler.authHandler

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - schema.graphql
